#############################################################################
# Makefile for building: ftpDemo
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  ftpDemo.pro
# Template: app
# Command: /home/wq/software/Qt5.8.0/5.8/gcc_64/bin/qmake -o Makefile ftpDemo.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../software/Qt5.8.0/5.8/gcc_64/include -I../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets -I../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui -I../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork -I../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++
QMAKE         = /home/wq/software/Qt5.8.0/5.8/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ftpDemo1.0.0
DISTDIR = /home/wq/workstation/qt/ftpDemo/.tmp/ftpDemo1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/wq/software/Qt5.8.0/5.8/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/wq/software/Qt5.8.0/5.8/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		maindialog.cpp \
		ftpmanager.cpp moc_maindialog.cpp \
		moc_ftpmanager.cpp
OBJECTS       = main.o \
		maindialog.o \
		ftpmanager.o \
		moc_maindialog.o \
		moc_ftpmanager.o
DIST          = ../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf \
		ftpDemo.pro maindialog.h \
		ftpmanager.h main.cpp \
		maindialog.cpp \
		ftpmanager.cpp
QMAKE_TARGET  = ftpDemo
DESTDIR       = 
TARGET        = ftpDemo


first: all
####### Build rules

$(TARGET): ui_maindialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ftpDemo.pro ../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf ../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf \
		ftpDemo.pro \
		../../../software/Qt5.8.0/5.8/gcc_64/lib/libQt5Widgets.prl \
		../../../software/Qt5.8.0/5.8/gcc_64/lib/libQt5Gui.prl \
		../../../software/Qt5.8.0/5.8/gcc_64/lib/libQt5Network.prl \
		../../../software/Qt5.8.0/5.8/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ftpDemo.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf:
../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf:
ftpDemo.pro:
../../../software/Qt5.8.0/5.8/gcc_64/lib/libQt5Widgets.prl:
../../../software/Qt5.8.0/5.8/gcc_64/lib/libQt5Gui.prl:
../../../software/Qt5.8.0/5.8/gcc_64/lib/libQt5Network.prl:
../../../software/Qt5.8.0/5.8/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ftpDemo.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents maindialog.h ftpmanager.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp maindialog.cpp ftpmanager.cpp $(DISTDIR)/
	$(COPY_FILE) --parents maindialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../software/Qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_maindialog.cpp moc_ftpmanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_maindialog.cpp moc_ftpmanager.cpp
moc_maindialog.cpp: ../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QDialog \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qdialog.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		maindialog.h \
		moc_predefs.h \
		../../../software/Qt5.8.0/5.8/gcc_64/bin/moc
	/home/wq/software/Qt5.8.0/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/wq/software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++ -I/home/wq/workstation/qt/ftpDemo -I/home/wq/software/Qt5.8.0/5.8/gcc_64/include -I/home/wq/software/Qt5.8.0/5.8/gcc_64/include/QtWidgets -I/home/wq/software/Qt5.8.0/5.8/gcc_64/include/QtGui -I/home/wq/software/Qt5.8.0/5.8/gcc_64/include/QtNetwork -I/home/wq/software/Qt5.8.0/5.8/gcc_64/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include maindialog.h -o moc_maindialog.cpp

moc_ftpmanager.cpp: ../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QObject \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/QSslConfiguration \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qsslsocket.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qsslerror.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcryptographichash.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qdatetime.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qssl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QFlags \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QString \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QSharedDataPointer \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QMetaType \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/QNetworkReply \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QIODevice \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QVariant \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/QNetworkRequest \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QUrl \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		ftpmanager.h \
		moc_predefs.h \
		../../../software/Qt5.8.0/5.8/gcc_64/bin/moc
	/home/wq/software/Qt5.8.0/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/wq/software/Qt5.8.0/5.8/gcc_64/mkspecs/linux-g++ -I/home/wq/workstation/qt/ftpDemo -I/home/wq/software/Qt5.8.0/5.8/gcc_64/include -I/home/wq/software/Qt5.8.0/5.8/gcc_64/include/QtWidgets -I/home/wq/software/Qt5.8.0/5.8/gcc_64/include/QtGui -I/home/wq/software/Qt5.8.0/5.8/gcc_64/include/QtNetwork -I/home/wq/software/Qt5.8.0/5.8/gcc_64/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ftpmanager.h -o moc_ftpmanager.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_maindialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_maindialog.h
ui_maindialog.h: maindialog.ui \
		../../../software/Qt5.8.0/5.8/gcc_64/bin/uic
	/home/wq/software/Qt5.8.0/5.8/gcc_64/bin/uic maindialog.ui -o ui_maindialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp maindialog.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QDialog \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qdialog.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QApplication \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qapplication.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qeventloop.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qguiapplication.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

maindialog.o: maindialog.cpp maindialog.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/QDialog \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qdialog.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		ui_maindialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maindialog.o maindialog.cpp

ftpmanager.o: ftpmanager.cpp ftpmanager.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QObject \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/QSslConfiguration \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qsslsocket.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qsslerror.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qcryptographichash.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qdatetime.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qssl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QFlags \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QString \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QSharedDataPointer \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QMetaType \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/QNetworkReply \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QIODevice \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QVariant \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/QNetworkRequest \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/QUrl \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		../../../software/Qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ftpmanager.o ftpmanager.cpp

moc_maindialog.o: moc_maindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maindialog.o moc_maindialog.cpp

moc_ftpmanager.o: moc_ftpmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ftpmanager.o moc_ftpmanager.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

